# Development environment, for a personal Notion instance

[people]
notion_people_id = "33e2df5d45ae80b3ad01f6b4a1cb90d7"
notion_people_uuid = "Person"
notion_people_email = "Email"
notion_people_github = "GitHub Profile"
notion_people_bugzilla = "Bugzilla Email"
notion_people_phabricator = "Phabricator Username"
notion_people_team = "Team"

[sync]


[sync.services]
method = "tracker_twoway"
tracker = "github"
notion_tasks_id = "3372df5d45ae808f83dcce2c88580ffa"
notion_milestones_id = "3372df5d45ae8099b384d3d8bb2b424d"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = ["2332df5d45ae8083af1dcda07b5c1eca", "31a2df5d45ae80d38897dd6efe4e134a"]

milestones_body_sync = false
milestones_body_sync_if_empty = true
tasks_body_sync = false
milestones_issue_type = "Milestone"

# Two-way directions (defaults shown explicitly)
tasks_tracker_to_notion = true
tasks_notion_to_tracker = true
milestones_tracker_to_notion = true
milestones_notion_to_tracker = true
tasks_conflict_preference = "notion"
milestones_conflict_preference = "notion"

tasks_tracker_to_notion_create = true
tasks_notion_to_tracker_create = true
milestones_tracker_to_notion_create = false
milestones_notion_to_tracker_create = false

[sync.services.repositories]

[sync.services.repositories.test]
repositories = [
  "thunderbird/test"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4Bg7Zd"
github_milestones_project_id = "PVT_kwDOAOe9Jc4Bg7NE"

#[sync.mobile.repositories.test2]
#repositories = [
#  "kewisch/test2"
#]
#github_tasks_project_id = "PVT_kwHOAAlD3s4A1bUZ"
#github_milestones_project_id = "PVT_kwHOAAlD3s4A1bUn"

[sync.services.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_planned_dates = "Original Due Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_estimate = "Estimate"
notion_tasks_review_url = "Patch URL"
notion_tasks_reviewers = "Peer Reviewer"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
#notion_tasks_sprint_relation = "Sprint"
notion_tasks_text_assignee = ""
notion_tasks_labels = "Keywords (Services)"
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done", "Canceled"]
notion_tasks_repository = "Product (Services)"

[sync.services.properties.notion_tasks_repository_map]
"thunderbird/test" = "Core Services"


#[sync.bugzilla]
#method = "tracker_twoway"
#tracker = "bugzilla"
#tracker_dry_run = true
#notion_tasks_id = "20edea4adcdf80b782faf2011506f86e"
#notion_milestones_id = "20edea4adcdf8064878af1281be913c8"
#bugzilla_base = "https://bugzilla.mozilla.org"
#milestones_tracker_prefix = "[meta] "
#
## Two-way directions (defaults shown explicitly)
#tasks_tracker_to_notion = true
#tasks_notion_to_tracker = false
#milestones_tracker_to_notion = false
#milestones_notion_to_tracker = true
#
#[sync.bugzilla.properties]
#notion_tasks_title = "Name"
#notion_tasks_assignee = "Assignee"
#notion_milestones_title = "Name"
#notion_issue_field = "Bugzilla Issue"
#notion_tasks_milestone_relation = "Milestone"
#notion_tasks_priority_values = ["P1", "P2", "P3", "P4", "P5"]

[sync.services_real]
method = "tracker_twoway"
tracker = "github"
notion_tasks_id = "3372df5d45ae808f83dcce2c88580ffa"
notion_milestones_id = "3372df5d45ae8099b384d3d8bb2b424d"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = ["2332df5d45ae8083af1dcda07b5c1eca", "31a2df5d45ae80d38897dd6efe4e134a"]

milestones_body_sync = false
milestones_body_sync_if_empty = true
tasks_body_sync = false
milestones_issue_type = "Milestone"

# Two-way directions (defaults shown explicitly)
tasks_tracker_to_notion = true
tasks_notion_to_tracker = false #changed
milestones_tracker_to_notion = true
milestones_notion_to_tracker = false #changed
tasks_conflict_preference = "notion"
milestones_conflict_preference = "notion"

tasks_tracker_to_notion_create = true
tasks_notion_to_tracker_create = false # changed
milestones_tracker_to_notion_create = true
milestones_notion_to_tracker_create = false # changed

[sync.services_real.repositories]
repositories = [
  "thunderbird/appointment"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4Bg7Zd"
github_milestones_project_id = "PVT_kwDOAOe9Jc4Bg7NE"

[sync.services_real.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_planned_dates = "Original Due Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_estimate = "Estimate"
notion_tasks_review_url = "Patch URL"
notion_tasks_reviewers = "Peer Reviewer"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
#notion_tasks_sprint_relation = "Sprint"
notion_tasks_text_assignee = ""
notion_tasks_labels = "Keywords (Services)"
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done", "Canceled"]
notion_tasks_repository = "Product (Services)"

[sync.services_real.properties.notion_tasks_repository_map]
"thunderbird/appointment" = "Appointment"

[sync.services_real_real]
method = "tracker_twoway"
tracker = "github"
#dry = true

twoway_cache_enabled = true
twoway_cache_path = ".cache/mzla-notion/services.sqlite3"

notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"
#notion_epics_id = "2332df5d45ae803dbebad6d6875f5399"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = ["2332df5d45ae8083af1dcda07b5c1eca", "31a2df5d45ae80d38897dd6efe4e134a"]


# Tasks sync
tasks_conflict_preference = "notion"
tasks_body_sync = false

tasks_tracker_to_notion = true
tasks_notion_to_tracker = false

tasks_tracker_to_notion_create = true
tasks_notion_to_tracker_create = false # changed



# Milestones
milestones_issue_type = "Milestone"
milestones_conflict_preference = "notion"
milestones_body_sync = false
milestones_body_sync_if_empty = true

milestones_tracker_to_notion = true
milestones_notion_to_tracker = true

milestones_tracker_to_notion_create = true
milestones_notion_to_tracker_create = false # changed

# Epics
epics_issue_type = "Epic"
epics_conflict_preference = "notion"
epics_allow_parents = true

epics_tracker_to_notion = true
epics_notion_to_tracker = true
epics_tracker_to_notion_create = true
epics_notion_to_tracker_create = false # changed

[sync.services_real_real.repositories]
repositories = [
    "thunderbird/addons-server",
    "thunderbird/appointment",
    "thunderbird/cloudops",
    "thunderbird/mailstrom",
    "thunderbird/observability",
    "thunderbird/platform-infrastructure",
    "thunderbird/pro",
    "thunderbird/pulumi",
    "thunderbird/services-ui",
    "thunderbird/services-utils",
    "thunderbird/tbpro-add-on",
    "thunderbird/thunderbird-accounts",
    "thunderbird/thunderbird-notifications",
    "thunderbird/thunderbird-website",
    "thunderbird/thundernest-ansible",
    "thunderbird/routing",
    "thunderbird/stormbox",
]
github_milestones_project_id = "PVT_kwDOAOe9Jc4BC48i"
github_tasks_project_id = "PVT_kwDOAOe9Jc4BC4_0"

[sync.services_real_real.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_planned_dates = "Original Due Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_estimate = "Estimate"
notion_tasks_review_url = "Patch URL"
notion_tasks_reviewers = "Peer Reviewer"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
#notion_tasks_sprint_relation = "Sprint"
notion_tasks_text_assignee = ""
notion_tasks_labels = "Keywords (Services)"
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done", "Canceled"]
notion_tasks_repository = "Product (Services)"


notion_milestones_epic_relation = "Epics"
notion_epics_team = "Teams"
notion_epics_title = "Name"
notion_epics_assignee = "Owner"
notion_epics_priority = "Priority"
notion_epics_status = "Status"
notion_epics_dates = "Target Date"

[sync.services_real_real.properties.notion_tasks_repository_map]
"thunderbird/addons-server" = "Core Services"
"thunderbird/appointment" = "Appointment"
"thunderbird/cloudops" = "Core Services"
"thunderbird/mailstrom" = "Thundermail"
"thunderbird/observability" = "Pro General"
"thunderbird/platform-infrastructure" = "Core Services"
"thunderbird/pro" = "Pro General"
"thunderbird/pulumi" = "Pro General"
"thunderbird/services-ui" = "Pro General"
"thunderbird/services-utils" = "Pro General"
"thunderbird/tbpro-add-on" = "Send"
"thunderbird/thunderbird-accounts" = "Accounts"
"thunderbird/thunderbird-notifications" = "Core Services"
"thunderbird/thunderbird-website" = "Websites"
"thunderbird/thundernest-ansible" = "Core Services"
"thunderbird/routing" = "Pro General"
"thunderbird/stormbox" = "Thundermail"
