---
name: CI

on:
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rye
        uses: eifinger/setup-rye@6dc1fff0a98becbcc0cf542a05ae144c9f32b100  # v4.2.8
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rye Sync
        run: rye sync

      - name: Rye Lint
        env:
          VERBOSE: ${{ runner.debug && '-v' || '' }}
        run:
          rye lint ${VERBOSE}

      - name: Rye Format
        env:
          VERBOSE: ${{ runner.debug && '-v' || '' }}
        run:
          rye fmt --check ${VERBOSE}
