---
name: Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths:
      - config/**
      - mzla_notion/**

concurrency:
  group: cron
  cancel-in-progress: false

jobs:
  synchronize:
    if: ${{ github.repository_owner == 'thunderbird' && (github.event_name != 'push' || !contains(github.event.head_commit.message || '', '[skip-sync]')) }}
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      environment: production
